---

ip_address: PUT_IP_ADDRESS_HERE

combine_password: combine

mysql_password: combine

spark_version: 2.0.1

livy_version: 0.3.0

scala_version: 2.11

hadoop_prefix: /opt/hadoop

hadoop_version: 2.7.4

hadoop_version_short: 2.7

elasticsearch_hadoop_connector_version: 5.6.2

basic_packages:
  - openssh-server
  - build-essential
  - unzip
  - libxml2-dev
  - libxslt1-dev
  - python-dev
  - python-setuptools
  - zlib1g-dev
  - git
  - vim
  - wget
  - curl
  - htop
  - tree
  - ncdu
  - mysql-server
  - libmysqlclient-dev
  - python-mysqldb
  - bc
  - maven
  - zip
  - python-software-properties

pip_packages:
  - jupyter
  - setuptools

java_packages:
  - oracle-java8-installer
  - oracle-java8-set-default

elasticsearch_http_port: 9200
elasticsearch_transport_tcp_port: 9300
elasticsearch_network_host: 0.0.0.0
elasticsearch_instance_name: "combine"
elasticsearch_heap_size: "1g"