---


- name: elasticsearch
  hosts: all
  become: yes
  gather_facts: true

  roles:
    - { role: elasticsearch,
      es_config: {
          http.port: 9200,
          transport.tcp.port: 9300,
          network.host: 0.0.0.0,
          }
      }
  vars:
    es_instance_name: "combine"

  tasks:

    - name: Copy elasticsearch JVM options to ES instance
      template: 
        src: jvm.options
        dest: /etc/elasticsearch/jvm.options
      notify: restart elasticsearch

  handlers:
    - name: restart elasticsearch
      service: name=combine_elasticsearch state=restarted
