---


- name: elasticsearch
  hosts: all
  become: yes
  gather_facts: true

  roles:

    - { role: elasticsearch,
      es_config: {
          http.port: "{{ elasticsearch_http_port }}",
          transport.tcp.port: "{{ elasticsearch_transport_tcp_port }}",
          network.host: "{{ elasticsearch_network_host }}",
          }
      }
  vars:
    es_instance_name: "{{ elasticsearch_instance_name }}"
    es_heap_size: "{{ elasticsearch_heap_size }}"
