---


- name: ingestion3
  hosts: all
  become: yes
  gather_facts: true

  tasks:

    - name: Is Ingestion3 already installed?
      stat: 
        path: /opt/ingestion3/
      register: ingestion3_installed
      changed_when: ingestion3_installed.stat.exists == False

    - name: Clone Ingestion3 from github repo
      git:
        repo: 'https://github.com/WSULIb/ingestion3.git'
        dest: /opt/ingestion3
        clone: yes
        update: no
      when: ingestion3_installed.stat.exists == False

    - name: Install ingestion3
      shell: |
        cd /opt/ingestion3
        sbt package
      args:
        executable: /bin/bash
      when: ingestion3_installed.stat.exists == False

    - name: Give combine user ownership over Ingestion3 directory
      file:
        dest: /opt/ingestion3
        owner: combine
        group: combine
        recurse: yes
      when: ingestion3_installed.stat.exists == False