---

- name: nginx
  hosts: all
  become: yes
  gather_facts: false

  tasks:

    - name: Is Nginx already installed?
      stat: 
        path: /etc/nginx
      register: nginx_installed
      changed_when: nginx_installed.stat.exists == False

    - name: install latest version of Nginx HTTP server
      package:
        name: nginx
        state: latest
        update_cache: yes
      when: nginx_installed.stat.exists == False

    - name: Copy the combine.nginx file to the Nginx application folder
      template: 
        src: combine.nginx
        dest: /etc/nginx/sites-available/combine
      when: nginx_installed.stat.exists == False

    - name: make a symlink from sites-available/combine vhost file to sites-enabled
      file:
        src: /etc/nginx/sites-available/combine
        dest: /etc/nginx/sites-enabled/combine
        state: link
        force: yes
      notify: restart nginx
      when: nginx_installed.stat.exists == False

  handlers:    
    - name: restart nginx
      service:
        name: nginx
        state: restarted