---

- hosts: all
  become: yes

  roles:
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - andrewrothstein.miniconda

- import_playbook: update-upgrade.yml
- import_playbook: bootstrap.yml
- import_playbook: apache.yml