- src: geerlingguy.java

- src: geerlingguy.elasticsearch
  name: elasticsearch
  version: 2.1.3

- src: https://github.com/andrewrothstein/ansible-miniconda.git
  name: miniconda
  version: v5.1.2

- src: https://github.com/andrewrothstein/ansible-spark.git
  name: spark
  version: v2.0.0