---

dependencies:
  - { role: elasticsearch,
    es_config: {
        http.port: "{{ elasticsearch_http_port }}",
        transport.tcp.port: "{{ elasticsearch_transport_tcp_port }}",
        network.host: "{{ elasticsearch_network_host }}",
        }
    }
